### PR TITLE
execv: fix execv returns 0 and doesn't set errno

### LINKED ISSUE #1335: execv return 0 and does not set errno on errors
Look at #1334 to reproduce this bug

```
	/* difference from posix: execv return 0 and does not set errno on errors */
	if (optind < argc) {
		execv(argv[optind], argv+optind);
		printf("env: execv: No such command '%s'\n", argv[optind]);
		return -ENOENT;
	}
```

### LINKED ISSUE #1702: service_run() does not consider result of starting service
```
static int service_run(const char *path, char *const argv[]) {
	pid_t pid;
	pid = vfork();

	if (pid < 0) {
		int err = errno;
		printf("vfork() error(%d): %s", err, strerror(err));
		return -err;
	}

	if (pid == 0) {
		execv(path, argv);
		exit(1);
	}
	service_add(path, pid);

	return 0;
}
```

in spite of execv() can be broken service always adding to services list

It's blocked by #1335

### PR DESCRIPTION
**Pull request by Ahish9009**
Closes #1335:
Behaves like execv in posix: returns -1 on failure and sets errno to the value of error that occurred. Seems to have fixed #1334, but does not seem to have helped #1702.

### CODE REVIEW

**Comment by Ahish9009** [comment]
Not sure what's wrong in the last check. Seems to have stopped while pinging 10.0.2.10.
Don't see why my changes should have affected it.

**Comment by anton-bondarev** [comment]
> Not sure what's wrong in the last check. Seems to have stopped while pinging 10.0.2.10.
> Don't see why my changes should have affected it.

Don't worry about this. It's not your fault. We restarted CI and it passed succeed

**Comment by anton-bondarev** [comment]
@Ahish9009 Hi, Thanks
I think You on the right way.
But Why do you want to differ in two situations

1. When cmd_exec return with errors
2. When cmd has not been found

I supposed You can just return ecode from exec_call and then return it in execv

**Comment by Ahish9009** [comment]
I had a look at the ```cmd_exec``` code and realised that the check for whether the command exists is happening already, but is returning EINVAL instead of ENOENT, which I fixed.
Further, not testing whether the cmd exists in ```exec_call()``` caused the issue of passing a NULL pointer to ```cmd2mod()```, which is also fixed now.
Please have a look at the changes.

File: src/cmds/sys/env.c [hunk 1]
```diff
@@ -68,8 +68,7 @@ int main(int argc, char *argv[]) {
 	/* difference from posix: execv return 0 and does not set errno on errors */
 	if (optind < argc) {
 		execv(argv[optind], argv+optind);
-		printf("env: execv: No such command '%s'\n", argv[optind]);
```
Comment (anton-bondarev) [inline src/cmds/sys/env.c]: I think It's better to keep printf but the message change to "env: execv: command '%s' failed with error code %d"

File: src/include/framework/cmd/types.h [hunk 2]
```diff
@@ -37,6 +37,7 @@ struct cmd_mod {
 };
 
 static inline const struct mod *cmd2mod(const struct cmd *cmd) {
+	if (!cmd) return NULL;
```
Comment (anton-bondarev) [inline src/include/framework/cmd/types.h]: I think You should check this before calling cmd2mod

File: src/compat/posix/proc/exec.c [hunk 3]
```diff
@@ -55,18 +57,10 @@ int exec_call(void) {
 		const struct cmd *cmd;
 
 		cmd = cmd_lookup(cmd_name);
-
```
Comment (anton-bondarev) [inline src/compat/posix/proc/exec.c]: Why you remove this?
Revert please

File: src/cmds/sys/env.c (hunk 1 above)
Comment (Ahish9009) [reply src/cmds/sys/env.c]: Okay, will make this change, but that'll mean I'll be printing errno(since ecode won't be returned from execv, as POSIX requires execv to return -1 on errors). 
So if I'm printing errno, isn't it better to use perror()?

File: src/compat/posix/proc/exec.c (hunk 3 above)
Comment (Ahish9009) [reply src/compat/posix/proc/exec.c]: I removed it because cmd_exec checks if the cmd exists anyways, so found that this check is redundant. Should I revert back though?

File: src/include/framework/cmd/types.h (hunk 2 above)
Comment (Ahish9009) [reply src/include/framework/cmd/types.h]: I did this so that I don't have to perform this check in the exec_call() function.

File: src/cmds/sys/env.c (hunk 1 above)
Comment (anton-bondarev) [reply src/cmds/sys/env.c]: Ok, just remove.
Thanks

File: src/compat/posix/proc/exec.c (hunk 3 above)
Comment (anton-bondarev) [reply src/compat/posix/proc/exec.c]: Yes, I see. But I don't understand why did you move checking from here? Why did you place it in cmd2mod(). why did you move it at all?

File: src/framework/cmd/core.c [hunk 4]
```diff
@@ -23,8 +23,10 @@ extern void getopt_init(void);
 int cmd_exec(const struct cmd *cmd, int argc, char **argv) {
 	int err;
 
-	if (!cmd)
-		return -EINVAL;
+	if (!cmd) {
```
Comment (anton-bondarev) [inline src/framework/cmd/core.c]: the same question.
Why did you change src/framework/cmd/core.c?
why you could not do it in src/compat/posix/proc/exec.c?

File: src/compat/posix/proc/exec.c (hunk 3 above)
Comment (Ahish9009) [reply src/compat/posix/proc/exec.c]: My aim was to remove setting errno to ENOENT in the exec_call() function, so I removed the check in exec_call() and simply used the check already present in cmd_exec(). 
On running however, as cmd was NULL, cmd2mod() caused errors as it was trying to perform its operation on a NULL pointer. So I included the check there too.
So should I put the check back here and remove the check in cmd2mod()?

File: src/framework/cmd/core.c (hunk 4 above)
Comment (Ahish9009) [reply src/framework/cmd/core.c]: It can be done in either place, but I thought it'd be better to do it in the cmd_exec() function as the error is during execution of the cmd, but I can revert back if needed, not a problem :)

File: src/compat/posix/proc/exec.c (hunk 3 above)
Comment (anton-bondarev) [reply src/compat/posix/proc/exec.c]: > My aim was to remove setting ecode and errno to ENOENT
Why? :)

I thought your aim is "execv returns 0 and doesn't set errno" :)

Comment (Ahish9009) [reply src/compat/posix/proc/exec.c]: > But Why do you want to differ in two situations
>
> When cmd_exec return with errors
> When cmd has not been found
> I supposed You can just return ecode from exec_call and then return it in execv

I thought when you said this in the earlier comment, you wanted me to set all errors in the cmd_exec() function itself, my bad. Should I revert it back to the way it was?

Comment (anton-bondarev) [reply src/compat/posix/proc/exec.c]: > Should I revert it back to the way it was?
Yes please.
I'm sorry that uncleanly put it

Comment (Ahish9009) [reply src/compat/posix/proc/exec.c]: Done :)

File: src/framework/cmd/core.c (hunk 4 above)
Comment (Ahish9009) [reply src/framework/cmd/core.c]: Reverted

File: src/include/framework/cmd/types.h (hunk 2 above)
Comment (Ahish9009) [reply src/include/framework/cmd/types.h]: Reverted

**Comment by anton-bondarev** [comment]
@Ahish9009 Thank you. I've approved PR.
Please rebase and squash commits

**Comment by Ahish9009** [comment]
> @Ahish9009 Thank you. I've approved PR.
> Please rebase and squash commits

Done
